name: Simple Workflow

# Add workflow_dispatch alongside push to allow manual triggering
on: 
  push:
    branches: 
      - main  
  workflow_dispatch:  # This enables manual triggering

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello, World!
        run: echo "MEOW!"
